### ISSUE TITLE
Bulk delete option for deleting members from a group

### ISSUE THREAD

**Issue by SurendraYellu** [topcoder-platform/group-manager-client#33]
In group manager tool, deleting a member is difficult if the group has more number of users. Some TopGear groups has more than a 1000 members.

The group members page loads 10 members at a time and have to scroll down till the bottom until all members data is loaded. then have to delete each record one by one.

It will be helpful if bulk delete option can be added. This option should take the list of email ids and delete them from a group.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , verified on dev.
However, when all the members are loaded in the members tab and when we bulk delete members, the deleted members are not removed form the members tab immediately. We need to load the  group page again for the member tab to be updated.


https://user-images.githubusercontent.com/58783823/154633060-9cfba49f-e230-49c3-a7e1-50dbfc3a9b24.mov

**Comment by SathyaJayabal** [comment]
this is released
https://topcoder.atlassian.net/browse/PLAT-616

**Comment by SathyaJayabal** [comment]
@SurendraYellu , the bulk delete option has now been added.

**Comment by SurendraYellu** [comment]
Thank you @sachin-maheshwari @SathyaJayabal for enabling this option.
